ngpu: 1
num_workers: 4
pin_memory: true
seed: null
batch_size: 64
num_epochs: 10000
save_every: 100
lr: 0.0004
lr_decay: 1.0
weight_decay: 0.0
dropout_rate: 0.1
loss_dvdw_ratio: 10.0
## Following are relative to `hydra.run.dir`.
checkpoint_dir: ckpt
tensorboard_dir: runs
log_file: ${hydra:job.name}.log
restart_file:
