_target_: models.pignet.PIGNet
n_gnn: 3
dim_gnn: 128
dim_mlp: 128
interconv: true
vdw_N_short: 6
vdw_N_long: 6
rotor_penalty: true
conv_range: [0.5, 5.0]
interaction_range: [0.5, 999.0]
dev_vdw_radii_coeff: 0.2
vdw_epsilon_scale: [0.0178, 0.0356]
hydrogen_bond_cutoffs: [-0.7, 0.0]
metal_ligand_cutoffs: [-0.7, 0.0]
hydrophobic_cutoffs: [0.5, 1.5]
# Current 'ionic_cutoffs' values are arbitrary!
include_ionic: false
ionic_cutoffs: [-101.0, -100.0]
